#!/bin/sh

err() {
   echo
   for msg; do
      echo $msg
   done
   echo "See http://code.google.com/p/maatkit/wiki/Testing for more information."
   echo
}

# ###########################################################################
# Sanity check the cmd line options.
# ###########################################################################
if [ $# -lt 1 ]; then
   err "Usage: load-sakila-db port"
   exit 1
fi

PORT=$1

if [ ! -d "/tmp/$PORT" ]; then
   err "Sandbox does not exist: /tmp/$PORT"
   exit 1
fi

# ###########################################################################
# Sanity check the environment.
# ###########################################################################
if [ -z "$MAATKIT_TRUNK" ]; then
   err "MAATKIT_TRUNK environment variable is not set."
   exit 1
fi

if [ ! -d "$MAATKIT_TRUNK" ]; then
   err "Invalid Maakit trunk directory: $MAATKIT_TRUNK"
   exit 1
fi

cd $MAATKIT_TRUNK/sandbox

/tmp/$PORT/use < sakila-db/sakila-schema.sql
/tmp/$PORT/use < sakila-db/sakila-data.sql

exit 0
