#!/bin/sh

NUM=$1

if [ -z "$1" ]; then
   echo "Must specify a sandbox to make!";
   exit 1;
fi

if [ $1 -le 1024 ]; then
   echo "Port number has to be > 1024";
   exit 1;
fi

DIR=`realpath $0`
cd `dirname $DIR`

PIDFILE="/tmp/$NUM/data/mysql_sandbox$NUM.pid"
if [ -f $PIDFILE ]; then
   echo "sandbox $NUM already started (found pid file $PIDFILE)"
else
   mkdir /tmp/$NUM
   tar xzf server.tar.gz -C /tmp/$NUM
   for file in `grep -rl NODE /tmp/$NUM`; do
      sed -i -e "s/NODE/$NUM/g" $file;
   done
   /tmp/$NUM/start
fi

/tmp/$NUM/use -e 'show innodb status' > /dev/null 2>&1
if [ "$?" != "0" ]; then
   echo "****** WARNING sandbox doesn't have a working InnoDB! ******"
   exit 1;
fi
