#!/bin/sh

nd="$MAATKIT_WORKING_COPY/doc/naturaldocs/NaturalDocs";
project="$MAATKIT_WORKING_COPY/doc/nd-conf/";
source="$MAATKIT_WORKING_COPY/doc/nd-temp/"
output="$MAATKIT_WORKING_COPY/doc/code/"

copy_code_to_source() {
   if [ ! -d $source ]; then
      mkdir $source
      mkdir $source/modules
      mkdir $source/tools
   fi

   cp $MAATKIT_WORKING_COPY/common/*.pm $source/modules

   for tool in $MAATKIT_WORKING_COPY/mk-*/mk-*; do
      tool=`basename $tool`
      $MAATKIT_WORKING_COPY/maatkit/extract-tool-package $tool > $source/tools/$tool
   done;
}

tool="$1"
if [ -n $tool ]; then
   $MAATKIT_WORKING_COPY/maatkit/extract-tool-package $tool > $source/tools/$tool
else
   copy_code_to_source
fi

$nd --project $project  --source $source -o HTML $output

if [ ! -f "$MAATKIT_WORKING_COPY/doc/keep-nd-temp" ]; then
   rm -rf $source >/dev/null
fi

exit
