#!/bin/sh

nd="$MAATKIT_WORKING_COPY/doc/naturaldocs/NaturalDocs";
project="$MAATKIT_WORKING_COPY/doc/nd-conf/";
source="$MAATKIT_WORKING_COPY/doc/nd-temp/"
output="$MAATKIT_WORKING_COPY/doc/code/"

copy_code_to_source() {
   if [ ! -d $source ]; then
      mkdir $source
      mkdir $source/modules
      mkdir $source/tools
   fi

   cp $MAATKIT_WORKING_COPY/common/*.pm $source/modules

   for tool in $MAATKIT_WORKING_COPY/mk-*/mk-*; do
      tool=`basename $tool`
      $MAATKIT_WORKING_COPY/maatkit/extract-tool-package $tool > $source/tools/$tool
   done;
}

tool=$1
if [ -n "$tool" ]; then
   if [ -f "$MAATKIT_WORKING_COPY/common/$tool" ]; then
      echo "Generating Natural Docs output for $tool..."
      cp "$MAATKIT_WORKING_COPY/common/$tool" $source/modules/
   elif [ -f "$MAATKIT_WORKING_COPY/$tool/$tool" ]; then
      echo "Generating Natural Docs output for $tool..."
      $MAATKIT_WORKING_COPY/maatkit/extract-tool-package $tool > $source/tools/$tool
   else
      echo "$tool is not a module or a tool";
      exit 1;
   fi
else
   echo "Generating Natural Docs output for the entire Maatkit code base..."
   copy_code_to_source
fi

extra_opts=""
if [ -f "$MAATKIT_WORKING_COPY/doc/rebuild" ]; then
   extra_opts="$extra_opts --rebuild"
fi

$nd --project $project  --source $source -o HTML $output $extra_opts

rm -rf "$MAATKIT_WORKING_COPY/doc/rebuild" >/dev/null

if [ ! -f "$MAATKIT_WORKING_COPY/doc/keep-nd-temp" ]; then
   rm -rf $source >/dev/null
fi

exit
