#!/usr/bin/perl

use strict;
use warnings FATAL => 'all';

# If the first argument is a number, it's that many days back to look for
# changes.  Default is 3.
my $d = 3;
if ( @ARGV && $ARGV[0] =~ m/^\d+$/ ) {
   $d = shift @ARGV;
   $d = `date -d "$d days ago" +%F`;
}
else {
   $d = `date -d "3 days ago" +%F`;
}

my @packages = @ARGV;
if ( !@packages ) {
  @packages = sort split(/\n/, `cat packages`);
}

foreach my $package ( @packages ) {
   # Find the desired version number and changelog.
   my $file;
   open($file, "<", "../$package/Changelog")
      or die $!;
   my $contents = do { local $/ = undef; <$file>; };
   close $file;
   die "$package has a tab in its changelog"
      if $contents =~ m/\t/;
   my ($log) = $contents =~ m/^(20[0-9].*?)(?=^20[0-9]|\Z)/sm;
   my ($date) = $log =~ m/^(\d{4}-\d\d-\d\d): version/;
   next unless $date ge $d;

   if ( @packages > 1 ) {
      print "Changelog for $package:\n\n";
   }
   $log =~ s/\s*$//gs;
   print $log, "\n\n";
}
