#!/usr/bin/perl

use strict;
use warnings FATAL => 'all';

# If the first argument is a number, it's that many days back to look for
# changes.  Default is 3.
my $d = 3;
if ( @ARGV && $ARGV[0] =~ m/^\d+$/ ) {
   $d = shift @ARGV;
}
$d = `mysql -e 'select current_date - interval $d day' -B --skip-column-names`;

my @packages = @ARGV;
if ( !@packages ) {
  @packages =
     map { m/(mk-.*)/g }
     grep { -f "$_/Changelog" }  <../mk-*>;
}

foreach my $package ( @packages ) {
   # Find the desired version number and changelog.
   my $file;
   open($file, "<", "../$package/Changelog")
      or die $!;
   my $contents = do { local $/ = undef; <$file>; };
   close $file;
   die "$package has a tab in its changelog"
      if $contents =~ m/\t/;
   my ($log) = $contents =~ m/^(200.*?)(?=^200|\Z)/sm;
   my ($date) = $log =~ m/^(\d{4}-\d\d-\d\d): version/;
   next unless $date ge $d;

   if ( @packages > 1 ) {
      print "Changelog for $package:\n\n";
   }
   $log =~ s/\s*$//gs;
   print $log, "\n\n";
}
