#!/bin/sh

exit_status=0
scriptno=0
pass=0
fail=0

for script in `cat packages`; do
   cd $MAATKIT_TRUNK/$script/t
   prove
   if [ $? -ne 0 ]; then
      exit_status=$?
      res[$scriptno]="$(printf "%-25s %-s" $script 'FAIL')"
      fail=$(($fail+1))
   else
      res[$scriptno]="$(printf "%-25s %-s" $script 'pass')"
      pass=$(($pass+1))
   fi
   echo
   scriptno=$(($scriptno+1))
done

# Change internal field separator so the result messages stay together.
ORIGINAL_IFS=$IFS
IFS=\012
for res in ${res[@]}; do
   echo "$res"
done
IFS=$ORIGINAL_IFS

echo
printf "pass: %2d\n" $pass
printf "FAIL: %2d\n" $fail

exit $exit_status
