#!/bin/bash
set -u
set -e
set -x

VERSION=`head -n 1 packlist | awk '{print $2}'`

RELEASE_TAR=release/maatkit-$VERSION.tar.gz

# Build the source tarball if necessary
if [ -f $RELEASE_TAR ]; then
   echo "Tarball already exists"
else
   echo "Building version $VERSION"
   perl ./package.pl
fi

# Create release-rpm directory
rm -rf release-rpm
mkdir release-rpm
cd release-rpm

# Build RPM package from the tarball
rpmbuild -ta ../$RELEASE_TAR

# Copy RPM package to release-rpm directory
if [ -f /usr/src/rpm/RPMS/noarch/maatkit-$VERSION-1.noarch.rpm ]; then
   cp /usr/src/rpm/RPMS/noarch/maatkit-$VERSION-1.noarch.rpm  .
else
   echo "RPM was not built"
fi

cd ..
