#!/bin/bash
set -u
set -e
set -x

VERSION=`head -n 1 packlist | awk '{print $2}'`

RELEASE_TAR=release/maatkit-$VERSION.tar.gz

# Build the source tarball if necessary
if [ -f $RELEASE_TAR ]; then
   echo "Tarball already exists"
else
   echo "Building version $VERSION"
   perl ./package.pl
fi

# Create working directory for all the temporary cruft
rm -rf release-rpm
mkdir release-rpm
cd release-rpm

# Extract and debianize source folders
cp ../$RELEASE_TAR maatkit-$VERSION.tar.gz

# Build RPM package from the tarball
cd maatkit-$VERSION
rpmbuild -ta maakit-$VERSION.tar.gz

if [ -f /usr/src/rpm/RPMS/noarch/maatkit-$VERSION-1.noarch.rpm ]; then
   cp /usr/src/rpm/RPMS/noarch/maatkit-$VERSION-1.noarch.rpm  .
else
   echo "RPM was not built"
fi

# Clean up unnecessary stuff
rm -rf maatkit-$VERSION
cd ..
