#!/bin/sh

set -e

for FILE in `ls ../mk-*/mk-*`; do
   if grep -q '^# [A-Z].* package.*Revision' $FILE; then
      echo "File $FILE has a malformed module header in it"
      grep '^# [A-Z].* package.*Revision' $FILE;
      exit 1;
   fi
   grep '^# [A-Z].* package [0-9]*$' $FILE | while read LINE; do
      MOD=`echo "$LINE" | awk '{print $2}'`;
      VER=`echo "$LINE" | awk '{print $4}'`;
      # Learn the version of that module...
      MVER=`grep Revision ../common/$MOD.pm | awk '{print $5}'`;
      if [ "$VER" -gt "$MVER" ]; then
         echo "$FILE has an impossible version $VER of $MOD (newest is $MVER)";
         exit 1;
      elif [ "$VER" != "$MVER" ]; then
         echo "$FILE has $MOD $VER; newest is $MVER";
      fi
   done
done
