#!/bin/sh

# This script controls Maatkit test coverage.

err() {
   echo
   for msg; do
      echo $msg
   done
   echo "See http://code.google.com/p/maatkit/wiki/Testing for more information."
   echo
}

usage() {
   err "Usage: mk-test-coverage script|module|update-summaries"
}

reset_cover_db() {
   if [ -d "$cover_db" ]; then
      rm -rf $cover_db/*
   fi
}

update_summary() {
   if [ $type = 'script' ]; then
      coverage_files='mk*'
   else
      coverage_files='*'
   fi

   summary_file="$summary_dir/summary"
   rm -rf $summary_file >/dev/null

   tmp_file="/tmp/$type-summary.txt"
   echo "File                           stmt   bran   cond    sub    pod   time  total" > $tmp_file
   head -q -n 4 $summary_dir/$coverage_files | grep -v 'File ' | grep -v '\-\-'  >> $tmp_file

   mv $tmp_file $summary_file

   echo "Wrote summary to $summary_file"
}

test_coverage() {
   if [ $type = 'module' ]; then
      summary_dir="$cover_dir/common"
      coverage_file="$summary_dir/$file.pm"
      # Test coveage for just this module, not all modules.
      test_file="$file.t"
      cd $MAATKIT_TRUNK/common/t
   else
      summary_dir="$cover_dir"
      coverage_file="$summary_dir/$file"
      cd $MAATKIT_TRUNK/$file/t
   fi

   if [ -n "$test_file" ]; then
      prove --perl "perl -MDevel::Cover=-silent,1,-db,$cover_db,-ignore,.+,-select,$file" $test_file
   else
      prove --perl "perl -MDevel::Cover=-silent,1,-db,$cover_db,-ignore,.+,-select,$file"
   fi

   cover -report text -silent $cover_db > $coverage_file
   echo "Wrote coverage to $coverage_file"
}


# ###########################################################################
# Sanity check cmd line and env var.
# ###########################################################################
if [ $# -lt 1 ]; then
   usage
   exit 1
fi

file=$1

cover_dir="$MAATKIT_TRUNK/coverage"
cover_db="$cover_dir/cover_db"

# ###########################################################################
# Test script/module coverage.
# ###########################################################################

if [ -f "$MAATKIT_TRUNK/common/$file.pm" ]; then
   type='module'
elif [ -f "$MAATKIT_TRUNK/$file/$file" ]; then
   type='script'
elif [ "$file" = "update-summaries" ]; then
   type='module'
   summary_dir="$cover_dir/common"
   update_summary

   type='script'
   summary_dir="$cover_dir"
   update_summary

   exit 0
else
   usage
   exit 1
fi

reset_cover_db
test_coverage
update_summary

exit 0
