#!/bin/sh

if [ -z $MAATKIT_BASEDIR ]; then
   echo "The MAATKIT_BASEDIR environment variables is not set."
   exit 1;
fi;

COVERAGE_DIR=$MAATKIT_BASEDIR/coverage
COVER_DB=$COVERAGE_DIR/cover_db

reset_cover_db () {
   if [ -d $COVER_DB ]; then
      rm -rf $COVER_DB/*
   fi
}

test_coverage () {
   SCRIPT=`echo $1 | sed 's/\.t//'`
   TEST_SCRIPT="$SCRIPT.t"
   if [ -f ../$SCRIPT.pm ]; then
      BASE_SCRIPT="../$SCRIPT.pm"
      EXTENSION='.pm'
      SCRIPT_TYPE='Module'
      SUMMARY_DIR=$COVERAGE_DIR/common
      COVERAGE_FILE=$SUMMARY_DIR/$SCRIPT$EXTENSION
   elif [ -f ../$SCRIPT ]; then
      BASE_SCRIPT="../$SCRIPT"
      EXTENSION=''
      SCRIPT_TYPE='Script'
      SUMMARY_DIR=$COVERAGE_DIR
      COVERAGE_FILE=$SUMMARY_DIR/$SCRIPT$EXTENSION
   else
      echo "Cannot find base script for $1; tried ../$SCRIPT.pm and ../$SCRIPT"
      echo "Skipping $1"
      return 1
   fi

   echo "$SCRIPT_TYPE: $BASE_SCRIPT"
   echo "Test script: $TEST_SCRIPT"

   reset_cover_db

   perl -MDevel::Cover=-db,$COVER_DB,-ignore,'.+',-select,"$BASE_SCRIPT" $TEST_SCRIPT
   cover -report text -silent $COVER_DB > $COVERAGE_FILE
   echo "Wrote $SCRIPT$EXTENSION coverage to $COVERAGE_FILE"

   return
}

_write_summary () {
   if [ $SCRIPT_TYPE = "Script" ]; then
      FILES='mk*'
   else
      FILES='*'
   fi
   SUMMARY_FILE=$SUMMARY_DIR/summary
   rm -f $SUMMARY_FILE
   echo "File                           stmt   bran   cond    sub    pod   time  total" >> $SUMMARY_FILE
   head -q -n 4 $SUMMARY_DIR/$FILES | grep -v File | grep -v '\-\-'  >> $SUMMARY_FILE
   echo "Wrote coverage summary to $SUMMARY_FILE"
}

write_summary () {
   if [ $SCRIPT_TYPE = "Module" ]; then
      _write_summary $COVERAGE_DIR/common $COVERAGE_DIR/common/summary
   elif [ $SCRIPT_TYPE = "Script" ]; then
      _write_summary $COVERAGE_DIR $COVERAGE_DIR/summary
   elif [ $SCRIPT_TYPE = "All" ]; then
      SCRIPT_TYPE="Module"
      _write_summary $COVERAGE_DIR/common $COVERAGE_DIR/common/summary
      SCRIPT_TYPE="Script"
      _write_summary 'Script' $COVERAGE_DIR $COVERAGE_DIR/summary
   else
      echo "I don't know how to write a $SCRIPT_TYPE summary."
      exit
   fi
}

if [ -z "$1" ]; then
   echo
   echo "Usage: $0 SCRIPT|summary"
   echo
   echo "SCRIPT is a .t script with a corresponding ../SCRIPT[.pm]."
   echo "Coverage results are written to $COVERAGE_DIR."
   echo
   echo "Instead of SCRIPT, 'summary' causes the coverage/summary file to be updated."
   echo
   exit 1
fi

if [ ! -d $COVERAGE_DIR ]; then
   echo
   echo "The coverage directory $COVERAGE_DIR does not exist."
   echo "Create and svn add $COVERAGE_DIR."
   echo
   exit 1
fi

if [ $1 != "summary" ]; then
   for script in $@; do
      if [ -f $script ]; then
         test_coverage $script
      fi
   done
else
   SCRIPT_TYPE="All"
fi

write_summary

exit
