#!/bin/sh

# This scripts updates a single module in all scripts.
# Example: ./update-one-module OptionParser
# That causes OptionParser to be updated in all scripts
# which have an out-of-date version of the module.

if [ -z $1 ]; then
   echo "Specify a module to update in all scripts."
   echo "Usage: $0 MODULE"
   exit 1
fi

trunk=$MAATKIT_WORKING_COPY
cd $trunk/maatkit

for FILE in `ls ../mk-*/mk-* | cut -d'/' -f 2`; do
   ./update-modules $FILE $1
done
