#!/bin/sh

trunk=$MAATKIT_WORKING_COPY
if [ -z "$trunk" ]; then
   echo "MAATKIT_WORKING_COPY environment variable is not set."
   exit 1
fi

# The first argument is the package (tool) to update.  The optional second
# argument is the module within that package (you can only specify one; if you
# omit it, all are updated).

if [ -z $1 ]; then
   echo "Specify a package to update."
   echo "Usage: $0 PACKAGE [MODULE]"
   echo "If no MODULE is specified, then all out-of-date modules in PACKAGE are updated."
   exit 1
else
   PACK=$1
fi

if [ -n "$2" ]; then
   MODULE=$2;
else
   MODULE="";
fi

if [ ! -d $trunk/$PACK ]; then
   echo "$PACK doesn't exist."
   exit 1
fi

for FILE in `ls $trunk/$PACK/mk-*`
do
   echo "Updating modules in $FILE..."
   pkgs_updated=0
   for MOD in `grep 'End .* package' $FILE | awk '{print $3}'`
   do
      if [ -z "$MODULE" -o "$MOD" = "$MODULE" ]; then
         if [ -f "$trunk/common/$MOD.pm" ]; then
            if grep -q '^# [A-Z].* package.*Revision' $FILE; then
               echo "  ERROR: $FILE has a malformed module header:"
               grep '^# [A-Z].* package.*Revision' $FILE
               echo
               exit 1
            fi

            pkg_uncommitted=`svn status "$trunk/common/$MOD.pm"`
            if [ -n "$pkg_uncommitted" ]; then
               echo "  Skipping $MOD because it has uncommited changes"
               continue
            fi

            pkg_ver=`grep Revision $trunk/common/$MOD.pm | cut -d' ' -f5`
            if [ -z "$FORCE_UPDATE" ]; then
               pkg_ver_in_tool=`grep "^# $MOD package" $FILE  | cut -d' ' -f4`
            else
               pkg_ver_in_tool=0
            fi

            if [ -n "$MKDEBUG" ]; then
               echo "  has $MOD.pm r$pkg_ver_in_tool"
            fi
            if [ $pkg_ver_in_tool -lt $pkg_ver ]; then
               cat $FILE | $trunk/maatkit/insert_module $MOD 0 > $MOD.tmp
               cat $MOD.tmp > $FILE;
               echo "  Updated $MOD from r$pkg_ver_in_tool to r$pkg_ver"
               pkgs_updated=1
            fi
         else
            echo "  WARNING: $FILE uses nonexistent module $MOD\n"
         fi
         rm -f $MOD.tmp;
      fi
   done
   if [ $pkgs_updated -eq 0 ]; then
      echo "  All modules are up to date"
   fi
   echo
done
