#!/bin/bash
set -u
set -e
set -x

VERSION=`head -n 1 packlist | awk '{print $2}'`

RELEASE_TAR=release/maatkit-$VERSION.tar.gz

# Build the source tarball if necessary
if [ -f $RELEASE_TAR ]; then
   echo "Tarball already exists"
else
   echo "Building version $VERSION"
   perl ./package.pl
fi

# Bring Debian changelog up to date
if [ `whoami` = 'baron' ]; then
   export DEBEMAIL='bps7j@users.sourceforge.net'
   export DEBFULLNAME='Baron Schwartz'
fi
if ! head -n 1 debian/changelog | grep -q "($VERSION-1)"; then
    debchange -D unstable -v $VERSION-1 "New upstream release."
    svn ci -m 'Changelog' debian/changelog
fi

# Create working directory for all the temporary cruft
rm -rf release-debian
mkdir release-debian
cd release-debian

# Extract and debianize source folders
cp ../$RELEASE_TAR maatkit_$VERSION.orig.tar.gz
tar xzf maatkit_$VERSION.orig.tar.gz
rsync -a --exclude .svn ../debian/ maatkit-$VERSION/debian/

# Build Debian source and binary packages
cd maatkit-$VERSION
debuild -S -sa -us -uc
debuild -b -us -uc

# Clean up unnecessary stuff
cd ..
rm -rf maatkit-$VERSION
cd ..
