#!/bin/sh

set -e

if [ -z $1 ]; then
   echo "Specify a package to tag"
   exit 1
fi

set -u
PACK=$1

if [ ! -d ../$PACK ]; then
   echo "$PACK doesn't exist"
   exit 1
fi

VER=`grep VERSION ../$PACK/Makefile | head -n 1 | awk '{print $3}'`

if ! grep -q "version $VER" ../$PACK/Changelog; then
   echo "There's no Changelog entry for version $VER in $PACK";
   exit 1;
fi

if [ -z $VER ]; then
   echo "I can't find the version in $PACK"
   exit 1
fi

svn up ../../tags/$PACK

if [ -d ../../tags/$PACK/$PACK-$VER ]; then
   echo "That tag already exists"
   exit 1
fi

REV=`svn info https://maatkit.svn.sourceforge.net/svnroot/maatkit/ | grep Revision | awk '{print $2}'`

svn cp -m "Tagged from trunk at r$REV" \
   https://maatkit.svn.sourceforge.net/svnroot/maatkit/trunk/$PACK \
   https://maatkit.svn.sourceforge.net/svnroot/maatkit/tags/$PACK/$PACK-$VER
