#!/usr/bin/perl

use strict;
use warnings FATAL => 'all';

use Test::More tests => 42;

require "../mysql-visual-explain";

sub load_file {
   my ($file) = @_;
   open my $fh, "<", $file or die $!;
   my $contents = do { local $/ = undef; <$fh> };
   close $fh;
   return $contents;
}
my $e = new ExplainTree;
my $t;

$t = $e->parse('');
is_deeply( $t, undef, 'No valid input' );

$t = $e->parse( load_file('samples/impossible_where.sql') );
is_deeply(
   $t,
   {  type  => 'IMPOSSIBLE',
      id    => 1,
      rowid => 0,
   },
   'Impossible WHERE',
);

$t = $e->parse( load_file('samples/simple_partition.sql') );
is_deeply(
   $t,
   {  type     => 'Filesort',
      id       => 1,
      rowid    => 0,
      children => [
         {  type     => 'Table scan',
            rows     => 10,
            children => [
               {  type          => 'Table',
                  table         => 'trb1',
                  possible_keys => undef,
                  partitions    => 'p0,p1,p2,p3',
               },
            ],
         },
      ],
   },
   'Partition',
);

$t = $e->parse( load_file('samples/full_scan_sakila_film.sql') );
is_deeply(
   $t,
   {  type     => 'Table scan',
      id       => 1,
      rowid    => 0,
      rows     => 935,
      children => [
         {  type          => 'Table',
            table         => 'film',
            possible_keys => undef,
            partitions    => undef,
         }
      ]
   },
   'Simple scan',
);

$t = $e->parse( load_file('samples/actor_join_film_ref.sql') );
is_deeply(
   $t,
   {  type     => 'JOIN',
      children => [
         {  type     => 'Table scan',
            rows     => 952,
            id       => 1,
            rowid    => 0,
            children => [
               {  type          => 'Table',
                  table         => 'film',
                  possible_keys => 'PRIMARY',
                  partitions    => undef,
               }
            ],
         },
         {  type     => 'Bookmark lookup',
            id       => 1,
            rowid    => 1,
            children => [
               {  type          => 'Index lookup',
                  key           => 'film_actor->idx_fk_film_id',
                  key_len       => 2,
                  'ref'         => 'sakila.film.film_id',
                  rows          => 2,
                  possible_keys => 'idx_fk_film_id',
                  partitions    => undef,
               },
               {  type          => 'Table',
                  table         => 'film_actor',
                  possible_keys => 'idx_fk_film_id',
                  partitions    => undef,
               },
            ],
         },
      ],
   },
   'Simple join',
);

$t = $e->parse( load_file('samples/range_check.sql') );
is_deeply(
   $t,
   {  type     => 'JOIN',
      children => [
         {  type     => 'Filter with WHERE',
            id       => 1,
            rowid    => 0,
            children => [
               {  type     => 'Bookmark lookup',
                  children => [
                     {  type          => 'Index lookup',
                        rows          => 5,
                        key           => 'v->OXROOTID',
                        key_len       => 32,
                        'ref'         => 'const',
                        possible_keys => 'OXLEFT,OXRIGHT,OXROOTID',
                        partitions    => undef,
                     },
                     {  type          => 'Table',
                        table         => 'v',
                        possible_keys => 'OXLEFT,OXRIGHT,OXROOTID',
                        partitions    => undef,
                     },
                  ],
               },
            ],
         },
         {  type     => 'Table scan',
            id       => 1,
            rowid    => 1,
            rows     => 5,
            children => [
               {  type          => 'Table',
                  table         => 's',
                  possible_keys => 'OXLEFT',
                  partitions    => undef,
                  warning => 'Range checked for each record (index map: 0x4)',
               },
            ],
         },
      ],
   },
   'Join that uses a range check',
);

$t = $e->parse( load_file('samples/not_exists.sql') );
is_deeply(
   $t,
   {  type     => 'JOIN',
      children => [
         {  type          => 'Index scan',
            rows          => 951,
            id            => 1,
            rowid         => 0,
            key           => 'film->idx_fk_language_id',
            key_len       => 1,
            'ref'         => undef,
            possible_keys => undef,
            partitions    => undef,
         },
         {  type     => 'Distinct/Not-Exists',
            id       => 1,
            rowid    => 1,
            children => [
               {  type     => 'Filter with WHERE',
                  children => [
                     {  type          => 'Index lookup',
                        key           => 'film_actor->idx_fk_film_id',
                        key_len       => 2,
                        'ref'         => 'sakila.film.film_id',
                        rows          => 2,
                        possible_keys => 'idx_fk_film_id',
                        partitions    => undef,
                     },
                  ],
               },
            ],
         },
      ],
   },
   'Join that uses Not exists',
);

$t = $e->parse( load_file('samples/join_temporary_with_where_distinct.sql') );
is_deeply(
   $t,
   {  type     => 'JOIN',
      children => [
         {  type     => 'Table scan',
            rows     => undef,
            id       => 1,
            rowid    => 0,
            children => [
               {  type          => 'TEMPORARY',
                  table         => 'temporary(film)',
                  possible_keys => undef,
                  partitions    => undef,
                  children      => [
                     {  type     => 'Filter with WHERE',
                        children => [
                           {  type     => 'Table scan',
                              rows     => 951,
                              children => [
                                 {  type          => 'Table',
                                    table         => 'film',
                                    possible_keys => 'PRIMARY',
                                    partitions    => undef,
                                 },
                              ],
                           },
                        ],
                     },
                  ],
               },
            ],
         },
         {  type     => 'Distinct/Not-Exists',
            id       => 1,
            rowid    => 1,
            children => [
               {  type          => 'Index lookup',
                  key           => 'film_actor->idx_fk_film_id',
                  possible_keys => 'idx_fk_film_id',
                  partitions    => undef,
                  key_len       => 2,
                  'ref'         => 'sakila.film.film_id',
                  rows          => 2,
               },
            ],
         },
      ],
   },
   'Join that uses a temp table, WHERE, and Distinct',
);

$t = $e->parse( load_file('samples/simple_join_three_tables.sql') );
is_deeply(
   $t,
   {  type     => 'JOIN',
      children => [
         {  type     => 'JOIN',
            children => [
               {  type          => 'Index scan',
                  key           => 'actor_1->PRIMARY',
                  possible_keys => 'PRIMARY',
                  partitions    => undef,
                  key_len       => 2,
                  'ref'         => undef,
                  rows          => 200,
                  id            => 1,
                  rowid         => 0,
               },
               {  type          => 'Unique index lookup',
                  key           => 'actor_2->PRIMARY',
                  possible_keys => 'PRIMARY',
                  partitions    => undef,
                  key_len       => 2,
                  'ref'         => 'sakila.actor_1.actor_id',
                  rows          => 1,
                  id            => 1,
                  rowid         => 1,
               },
            ],
         },
         {  type          => 'Unique index lookup',
            key           => 'actor_3->PRIMARY',
            possible_keys => 'PRIMARY',
            partitions    => undef,
            key_len       => 2,
            'ref'         => 'sakila.actor_1.actor_id',
            rows          => 1,
            id            => 1,
            rowid         => 2,
         },
      ],
   },
   'Simple join over three tables',
);

$t = $e->parse( load_file('samples/film_join_actor_eq_ref.sql') );
is_deeply(
   $t,
   {  type     => 'JOIN',
      children => [
         {  type     => 'Table scan',
            rows     => 5143,
            id       => 1,
            rowid    => 0,
            children => [
               {  type          => 'Table',
                  table         => 'film_actor',
                  possible_keys => 'idx_fk_film_id',
                  partitions    => undef,
               },
            ]
         },
         {  type     => 'Bookmark lookup',
            id       => 1,
            rowid    => 1,
            children => [
               {  type          => 'Unique index lookup',
                  key           => 'film->PRIMARY',
                  key_len       => 2,
                  'ref'         => 'sakila.film_actor.film_id',
                  rows          => 1,
                  possible_keys => 'PRIMARY',
                  partitions    => undef,
               },
               {  type          => 'Table',
                  table         => 'film',
                  possible_keys => 'PRIMARY',
                  partitions    => undef,
               },
            ],
         },
      ],
   },
   'Straight join',
);

$t = $e->parse(
   load_file('samples/film_join_actor_eq_ref.sql'),
   { clustered => 1 },
);
is_deeply(
   $t,
   {  type     => 'JOIN',
      children => [
         {  type     => 'Table scan',
            rows     => 5143,
            id       => 1,
            rowid    => 0,
            children => [
               {  type          => 'Table',
                  table         => 'film_actor',
                  possible_keys => 'idx_fk_film_id',
                  partitions    => undef,
               },
            ]
         },
         {  type          => 'Unique index lookup',
            id            => 1,
            rowid         => 1,
            key           => 'film->PRIMARY',
            possible_keys => 'PRIMARY',
            partitions    => undef,
            key_len       => 2,
            'ref'         => 'sakila.film_actor.film_id',
            rows          => 1,
         },
      ],
   },
   'Straight join assuming clustered PK',
);

$t = $e->parse( load_file('samples/full_row_pk_lookup_sakila_film.sql') );
is_deeply(
   $t,
   {  type     => 'Bookmark lookup',
      id       => 1,
      rowid    => 0,
      children => [
         {  type          => 'Constant index lookup',
            key           => 'film->PRIMARY',
            key_len       => 2,
            'ref'         => 'const',
            rows          => 1,
            possible_keys => 'PRIMARY',
            partitions    => undef,
         },
         {  type          => 'Table',
            table         => 'film',
            possible_keys => 'PRIMARY',
            partitions    => undef,
         },
      ],
   },
   'Constant lookup',
);

$t = $e->parse( load_file('samples/index_scan_sakila_film.sql') );
is_deeply(
   $t,
   {  type     => 'Bookmark lookup',
      id       => 1,
      rowid    => 0,
      children => [
         {  type          => 'Index scan',
            key           => 'film->idx_title',
            key_len       => 767,
            'ref'         => undef,
            rows          => 952,
            possible_keys => undef,
            partitions    => undef,
         },
         {  type          => 'Table',
            table         => 'film',
            possible_keys => undef,
            partitions    => undef,
         },
      ],
   },
   'Index scan',
);

$t = $e->parse( load_file('samples/index_scan_sakila_film_using_where.sql') );
is_deeply(
   $t,
   {  type     => 'Filter with WHERE',
      id       => 1,
      rowid    => 0,
      children => [
         {  type     => 'Bookmark lookup',
            children => [
               {  type          => 'Index scan',
                  key           => 'film->idx_title',
                  key_len       => 767,
                  'ref'         => undef,
                  rows          => 952,
                  possible_keys => undef,
                  partitions    => undef,
               },
               {  type          => 'Table',
                  table         => 'film',
                  possible_keys => undef,
                  partitions    => undef,
               },
            ],
         },
      ],
   },
   'Index scan with WHERE clause',
);

$t = $e->parse( load_file('samples/pk_lookup_sakila_film.sql') );
is_deeply(
   $t,
   {  type          => 'Constant index lookup',
      key           => 'film->PRIMARY',
      possible_keys => 'PRIMARY',
      partitions    => undef,
      key_len       => 2,
      'ref'         => 'const',
      rows          => 1,
      id            => 1,
      rowid         => 0,
   },
   'PK lookup with covering index',
);

$t = $e->parse( load_file('samples/film_join_actor_const.sql') );
is_deeply(
   $t,
   {  type     => 'JOIN',
      children => [
         {  type     => 'Bookmark lookup',
            id       => 1,
            rowid    => 0,
            children => [
               {  type          => 'Constant index lookup',
                  key           => 'film->PRIMARY',
                  key_len       => 2,
                  'ref'         => 'const',
                  rows          => 1,
                  possible_keys => 'PRIMARY',
                  partitions    => undef,
               },
               {  type          => 'Table',
                  table         => 'film',
                  possible_keys => 'PRIMARY',
                  partitions    => undef,
               },
            ],
         },
         {  type     => 'Bookmark lookup',
            id       => 1,
            rowid    => 1,
            children => [
               {  type          => 'Index lookup',
                  key           => 'film_actor->idx_fk_film_id',
                  key_len       => 2,
                  'ref'         => 'const',
                  rows          => 10,
                  possible_keys => 'idx_fk_film_id',
                  partitions    => undef,
               },
               {  type          => 'Table',
                  table         => 'film_actor',
                  possible_keys => 'idx_fk_film_id',
                  partitions    => undef,
               },
            ],
         },
      ],
   },
   'Join from constant lookup in film to const ref in film_actor',
);

$t = $e->parse( load_file('samples/film_join_actor_const_using_index.sql') );
is_deeply(
   $t,
   {  type     => 'JOIN',
      children => [
         {  type          => 'Constant index lookup',
            key           => 'film->PRIMARY',
            possible_keys => 'PRIMARY',
            partitions    => undef,
            key_len       => 2,
            'ref'         => 'const',
            rows          => 1,
            id            => 1,
            rowid         => 0,
         },
         {  type          => 'Index lookup',
            key           => 'film_actor->idx_fk_film_id',
            possible_keys => 'idx_fk_film_id',
            partitions    => undef,
            key_len       => 2,
            'ref'         => 'const',
            rows          => 10,
            id            => 1,
            rowid         => 1,
         },
      ],
   },
   'Join from const film to const ref film_actor with covering index',
);

$t = $e->parse( load_file('samples/film_range_on_pk.sql') );
is_deeply(
   $t,
   {  type     => 'Filter with WHERE',
      id       => 1,
      rowid    => 0,
      children => [
         {  type     => 'Bookmark lookup',
            children => [
               {  type          => 'Index range scan',
                  key           => 'film->PRIMARY',
                  key_len       => 2,
                  'ref'         => undef,
                  rows          => 20,
                  possible_keys => 'PRIMARY',
                  partitions    => undef,
               },
               {  type          => 'Table',
                  table         => 'film',
                  possible_keys => 'PRIMARY',
                  partitions    => undef,
               },
            ],
         },
      ],
   },
   'Index range scan with WHERE clause',
);

$t = $e->parse( load_file('samples/loose_index_scan.sql') );
is_deeply(
   $t,
   {  type          => 'Loose index scan',
      key           => 'film->idx_fk_language_id',
      key_len       => 1,
      'ref'         => undef,
      rows          => 2,
      id            => 1,
      rowid         => 0,
      possible_keys => undef,
      partitions    => undef,
   },
   'Loose index scan',
);

$t = $e->parse(
   load_file('samples/film_ref_or_null_on_original_language_id.sql') );
is_deeply(
   $t,
   {  type     => 'Filter with WHERE',
      id       => 1,
      rowid    => 0,
      children => [
         {  type     => 'Bookmark lookup',
            children => [
               {  type          => 'Index lookup with extra null lookup',
                  key           => 'film->idx_fk_original_language_id',
                  key_len       => 2,
                  'ref'         => 'const',
                  rows          => 512,
                  possible_keys => 'idx_fk_original_language_id',
                  partitions    => undef,
               },
               {  type          => 'Table',
                  table         => 'film',
                  possible_keys => 'idx_fk_original_language_id',
                  partitions    => undef,
               },
            ],
         },
      ],
   },
   'Index ref_or_null scan',
);

$t = $e->parse( load_file('samples/rental_index_merge_intersect.sql') );
is_deeply(
   $t,
   {  type     => 'Filter with WHERE',
      id       => 1,
      rowid    => 0,
      children => [
         {  type     => 'Bookmark lookup',
            children => [
               {  type     => 'Index merge',
                  method   => 'intersect',
                  rows     => 1,
                  children => [
                     {  type => 'Index range scan',
                        key  => 'rental->idx_fk_inventory_id',
                        possible_keys =>
                           'idx_fk_inventory_id,idx_fk_customer_id',
                        partitions    => undef,
                        key_len => 3,
                        'ref'   => undef,
                        rows    => 1,
                     },
                     {  type => 'Index range scan',
                        key  => 'rental->idx_fk_customer_id',
                        possible_keys =>
                           'idx_fk_inventory_id,idx_fk_customer_id',
                        partitions    => undef,
                        key_len => 2,
                        'ref'   => undef,
                        rows    => 1,
                     },
                  ],
               },
               {  type          => 'Table',
                  table         => 'rental',
                  possible_keys => 'idx_fk_inventory_id,idx_fk_customer_id',
                  partitions    => undef,
               },
            ],
         },
      ],
   },
   'Index intersection merge',
);

$t = $e->parse( load_file('samples/index_merge_three_keys.sql') );
is_deeply(
   $t,
   {  type     => 'Filter with WHERE',
      id       => 1,
      rowid    => 0,
      children => [
         {  type     => 'Index merge',
            method   => 'intersect',
            rows     => 2,
            children => [
               {  type          => 'Index range scan',
                  key           => 't1->key1',
                  possible_keys => 'key1,key2,key3',
                  partitions    => undef,
                  key_len       => 5,
                  'ref'         => undef,
                  rows          => 2,
               },
               {  type          => 'Index range scan',
                  key           => 't1->key2',
                  possible_keys => 'key1,key2,key3',
                  partitions    => undef,
                  key_len       => 5,
                  'ref'         => undef,
                  rows          => 2,
               },
               {  type          => 'Index range scan',
                  key           => 't1->key3',
                  possible_keys => 'key1,key2,key3',
                  partitions    => undef,
                  key_len       => 5,
                  'ref'         => undef,
                  rows          => 2,
               },
            ],
         },
      ],
   },
   'Index intersection merge with three keys and covering index',
);

$t = $e->parse( load_file('samples/index_merge_union_intersect.sql') );
is_deeply(
   $t,
   {  type     => 'Filter with WHERE',
      id       => 1,
      rowid    => 0,
      children => [
         {  type     => 'Bookmark lookup',
            children => [
               {  type     => 'Index merge',
                  method   => 'union',
                  rows     => 154,
                  children => [
                     {  type     => 'Index merge',
                        method   => 'intersect',
                        rows     => 154,
                        children => [
                           {  type          => 'Index range scan',
                              key           => 't1->key1',
                              possible_keys => 'key1,key2,key3,key4',
                              partitions    => undef,
                              key_len       => 5,
                              'ref'         => undef,
                              rows          => 154,
                           },
                           {  type          => 'Index range scan',
                              key           => 't1->key2',
                              possible_keys => 'key1,key2,key3,key4',
                              partitions    => undef,
                              key_len       => 5,
                              'ref'         => undef,
                              rows          => 154,
                           },
                        ],
                     },
                     {  type     => 'Index merge',
                        method   => 'intersect',
                        rows     => 154,
                        children => [
                           {  type          => 'Index range scan',
                              key           => 't1->key3',
                              possible_keys => 'key1,key2,key3,key4',
                              partitions    => undef,
                              key_len       => 5,
                              'ref'         => undef,
                              rows          => 154,
                           },
                           {  type          => 'Index range scan',
                              key           => 't1->key4',
                              possible_keys => 'key1,key2,key3,key4',
                              partitions    => undef,
                              key_len       => 5,
                              'ref'         => undef,
                              rows          => 154,
                           },
                        ],
                     },
                  ],
               },
               {  type          => 'Table',
                  table         => 't1',
                  possible_keys => 'key1,key2,key3,key4',
                  partitions    => undef,
               },
            ],
         },
      ],
   },
   'Index merge union-intersection',
);

$t = $e->parse( load_file('samples/index_merge_sort_union.sql') );
is_deeply(
   $t,
   {  type     => 'Filter with WHERE',
      id       => 1,
      rowid    => 0,
      children => [
         {  type     => 'Bookmark lookup',
            children => [
               {  type     => 'Index merge',
                  method   => 'sort_union',
                  rows     => 45,
                  children => [
                     {  type          => 'Index range scan',
                        key           => 't0->i1',
                        possible_keys => 'i1,i2',
                        partitions    => undef,
                        key_len       => 4,
                        'ref'         => undef,
                        rows          => 45,
                     },
                     {  type          => 'Index range scan',
                        key           => 't0->i2',
                        possible_keys => 'i1,i2',
                        partitions    => undef,
                        key_len       => 4,
                        'ref'         => undef,
                        rows          => 45,
                     },
                  ],
               },
               {  type          => 'Table',
                  table         => 't0',
                  possible_keys => 'i1,i2',
                  partitions    => undef,
               },
            ],
         },
      ],
   },
   'Index merge sort_union',
);

$t = $e->parse( load_file('samples/optimized_away.sql') );
is_deeply(
   $t,
   {  type  => 'CONSTANT',
      id    => 1,
      rowid => 0,
   },
   'No tables used',
);

$t = $e->parse( load_file('samples/no_from.sql') );
is_deeply(
   $t,
   {  type  => 'DUAL',
      id    => 1,
      rowid => 0,
   },
   'No tables used',
);

$t = $e->parse( load_file('samples/filesort.sql') );
is_deeply(
   $t,
   {  type     => 'Filesort',
      id       => 1,
      rowid    => 0,
      children => [
         {  type     => 'Table scan',
            rows     => 951,
            children => [
               {  type          => 'Table',
                  table         => 'film',
                  possible_keys => undef,
                  partitions    => undef,
               },
            ],
         },
      ],
   },
   'Filesort',
);

$t = $e->parse( load_file('samples/temporary_filesort.sql') );
is_deeply(
   $t,
   {  type     => 'Filesort',
      id       => 1,
      rowid    => 0,
      children => [
         {  type     => 'Table scan',
            rows     => undef,
            children => [
               {  type          => 'TEMPORARY',
                  table         => 'temporary(film)',
                  possible_keys => undef,
                  partitions    => undef,
                  children      => [
                     {  type          => 'Index scan',
                        key           => 'film->PRIMARY',
                        possible_keys => undef,
                        partitions    => undef,
                        key_len       => 2,
                        'ref'         => undef,
                        rows          => 951,
                     },
                  ],
               },
            ],
         },
      ],
   },
   'Filesort',
);

$t = $e->parse( load_file('samples/simple_union.sql') );
is_deeply(
   $t,
   {  type     => 'Table scan',
      rows     => undef,
      id       => 1,
      rowid    => 2,
      children => [
         {  type          => 'UNION',
            possible_keys => undef,
            partitions    => undef,
            table         => 'union(actor_1,actor_2)',
            children      => [
               {  type          => 'Index scan',
                  key           => 'actor_1->PRIMARY',
                  possible_keys => undef,
                  partitions    => undef,
                  key_len       => 2,
                  'ref'         => undef,
                  rows          => 200,
                  id            => 1,
                  rowid         => 0,
               },
               {  type          => 'Index scan',
                  key           => 'actor_2->PRIMARY',
                  possible_keys => undef,
                  partitions    => undef,
                  key_len       => 2,
                  'ref'         => undef,
                  rows          => 200,
                  id            => 2,
                  rowid         => 1,
               },
            ],
         },
      ],
   },
   'Simple union',
);

$t = $e->parse( load_file('samples/simple_derived.sql') );
is_deeply(
   $t,
   {  type     => 'Table scan',
      rows     => 200,
      id       => 1,
      rowid    => 0,
      children => [
         {  type          => 'DERIVED',
            table         => 'derived(actor)',
            possible_keys => undef,
            partitions    => undef,
            children      => [
               {  type          => 'Index scan',
                  key           => 'actor->PRIMARY',
                  possible_keys => undef,
                  partitions    => undef,
                  key_len       => 2,
                  'ref'         => undef,
                  rows          => 200,
                  id            => 2,
                  rowid         => 1,
               },
            ],
         },
      ],
   },
   'Simple derived table',
);

$t = $e->parse( load_file('samples/derived_over_join.sql') );
is_deeply(
   $t,
   {  type     => 'Table scan',
      rows     => 40000,
      id       => 1,
      rowid    => 0,
      children => [
         {  type          => 'DERIVED',
            table         => 'derived(actor_1,actor_2)',
            possible_keys => undef,
            partitions    => undef,
            children      => [
               {  type     => 'JOIN',
                  children => [
                     {  type          => 'Index scan',
                        key           => 'actor_1->PRIMARY',
                        possible_keys => undef,
                        partitions    => undef,
                        key_len       => 2,
                        'ref'         => undef,
                        rows          => 200,
                        id            => 2,
                        rowid         => 1,
                     },
                     {  type          => 'Index scan',
                        key           => 'actor_2->PRIMARY',
                        possible_keys => undef,
                        partitions    => undef,
                        key_len       => 2,
                        'ref'         => undef,
                        rows          => 200,
                        id            => 2,
                        rowid         => 2,
                     },
                  ],
               },
            ],
         },
      ],
   },
   'Simple derived table over a simple join',
);

$t = $e->parse( load_file('samples/join_two_derived_tables_of_joins.sql') );
is_deeply(
   $t,
   {  type     => 'JOIN',
      children => [
         {  type     => 'Table scan',
            rows     => 40000,
            id       => 1,
            rowid    => 0,
            children => [
               {  type          => 'DERIVED',
                  table         => 'derived(actor_1,actor_2)',
                  possible_keys => undef,
                  partitions    => undef,
                  children      => [
                     {  type     => 'JOIN',
                        children => [
                           {  type          => 'Index scan',
                              key           => 'actor_1->PRIMARY',
                              possible_keys => undef,
                              partitions    => undef,
                              key_len       => 2,
                              'ref'         => undef,
                              rows          => 200,
                              id            => 2,
                              rowid         => 4,
                           },
                           {  type          => 'Index scan',
                              key           => 'actor_2->PRIMARY',
                              possible_keys => undef,
                              partitions    => undef,
                              key_len       => 2,
                              'ref'         => undef,
                              rows          => 200,
                              id            => 2,
                              rowid         => 5,
                           },
                        ],
                     },
                  ],
               },
            ],
         },
         {  type     => 'Filter with WHERE',
            id       => 1,
            rowid    => 1,
            children => [
               {  type     => 'Table scan',
                  rows     => 40000,
                  children => [
                     {  type          => 'DERIVED',
                        table         => 'derived(actor_3,actor_4)',
                        possible_keys => undef,
                        partitions    => undef,
                        children      => [
                           {  type     => 'JOIN',
                              children => [
                                 {  type          => 'Index scan',
                                    key           => 'actor_3->PRIMARY',
                                    possible_keys => undef,
                                    partitions    => undef,
                                    key_len       => 2,
                                    'ref'         => undef,
                                    rows          => 200,
                                    id            => 3,
                                    rowid         => 2,
                                 },
                                 {  type          => 'Index scan',
                                    key           => 'actor_4->PRIMARY',
                                    possible_keys => undef,
                                    partitions    => undef,
                                    key_len       => 2,
                                    'ref'         => undef,
                                    rows          => 200,
                                    id            => 3,
                                    rowid         => 3,
                                 },
                              ],
                           },
                        ],
                     },
                  ],
               },
            ],
         },
      ],
   },
   'Join two derived tables which each contain a join',
);

$t = $e->parse( load_file('samples/union_of_derived_tables.sql') );
is_deeply(
   $t,
   {  type     => 'Table scan',
      rows     => undef,
      id       => 1,
      rowid    => 4,
      children => [
         {  type          => 'UNION',
            table         => 'union(derived(actor),derived(film))',
            possible_keys => undef,
            partitions    => undef,
            children      => [
               {  type     => 'Table scan',
                  id       => 1,
                  rowid    => 0,
                  rows     => 200,
                  children => [
                     {  type          => 'DERIVED',
                        table         => 'derived(actor)',
                        possible_keys => undef,
                        partitions    => undef,
                        children      => [
                           {  type          => 'Index scan',
                              key           => 'actor->PRIMARY',
                              possible_keys => undef,
                              partitions    => undef,
                              key_len       => 2,
                              'ref'         => undef,
                              rows          => 200,
                              id            => 2,
                              rowid         => 1,
                           },
                        ],
                     },
                  ],
               },
               {  type     => 'Table scan',
                  id       => 3,
                  rowid    => 2,
                  rows     => 1000,
                  children => [
                     {  type          => 'DERIVED',
                        table         => 'derived(film)',
                        possible_keys => undef,
                        partitions    => undef,
                        children      => [
                           {  type          => 'Index scan',
                              key           => 'film->idx_fk_language_id',
                              possible_keys => undef,
                              partitions    => undef,
                              key_len       => 1,
                              'ref'         => undef,
                              rows          => 951,
                              id            => 4,
                              rowid         => 3,
                           },
                        ],
                     },
                  ],
               },
            ],
         },
      ],
   },
   'Union over two derived tables',
);

$t = $e->parse( load_file('samples/join_two_derived_tables_of_unions.sql') );
is_deeply(
   $t,
   {  type     => 'JOIN',
      children => [
         {  type     => 'Constant table access',
            id       => 1,
            rowid    => 0,
            rows     => 1,
            children => [
               {  type          => 'DERIVED',
                  table         => 'derived(union(actor_1,actor_2))',
                  possible_keys => undef,
                  partitions    => undef,
                  children      => [
                     {  type     => 'Table scan',
                        id       => 2,
                        rowid    => 7,
                        rows     => undef,
                        children => [
                           {  type          => 'UNION',
                              possible_keys => undef,
                              partitions    => undef,
                              table         => 'union(actor_1,actor_2)',
                              children      => [
                                 {  type          => 'Index scan',
                                    key           => 'actor_1->PRIMARY',
                                    possible_keys => undef,
                                    partitions    => undef,
                                    key_len       => 2,
                                    'ref'         => undef,
                                    rows          => 200,
                                    id            => 2,
                                    rowid         => 5,
                                 },
                                 {  type          => 'Index scan',
                                    key           => 'actor_2->PRIMARY',
                                    possible_keys => undef,
                                    partitions    => undef,
                                    key_len       => 2,
                                    'ref'         => undef,
                                    rows          => 200,
                                    id            => 3,
                                    rowid         => 6,
                                 },
                              ],
                           },
                        ],
                     }
                  ],
               },
            ],
         },
         {  type     => 'Constant table access',
            id       => 1,
            rowid    => 1,
            rows     => 1,
            children => [
               {  type          => 'DERIVED',
                  table         => 'derived(union(actor_3,actor_4))',
                  possible_keys => undef,
                  partitions    => undef,
                  children      => [
                     {  type     => 'Table scan',
                        id       => 4,
                        rowid    => 4,
                        rows     => undef,
                        children => [
                           {  type          => 'UNION',
                              possible_keys => undef,
                              partitions    => undef,
                              table         => 'union(actor_3,actor_4)',
                              children      => [
                                 {  type          => 'Index scan',
                                    key           => 'actor_3->PRIMARY',
                                    possible_keys => undef,
                                    partitions    => undef,
                                    key_len       => 2,
                                    'ref'         => undef,
                                    rows          => 200,
                                    id            => 4,
                                    rowid         => 2,
                                 },
                                 {  type          => 'Index scan',
                                    key           => 'actor_4->PRIMARY',
                                    possible_keys => undef,
                                    partitions    => undef,
                                    key_len       => 2,
                                    'ref'         => undef,
                                    rows          => 200,
                                    id            => 5,
                                    rowid         => 3,
                                 },
                              ],
                           },
                        ],
                     }
                  ],
               },
            ],
         },
      ],
   },
   'Join over two derived tables of unions',
);

$t = $e->parse( load_file('samples/union_of_derived_unions.sql') );
is_deeply(
   $t,
   {  type     => 'Table scan',
      rows     => undef,
      id       => 1,
      rowid    => 8,
      children => [
         {  type => 'UNION',
            table =>
               'union(derived(union(actor_1,actor_2)),derived(union(actor_3,actor_4)))',
            possible_keys => undef,
            partitions    => undef,
            children      => [
               {  type     => 'Constant table access',
                  id       => 1,
                  rowid    => 0,
                  rows     => 1,
                  children => [
                     {  type          => 'DERIVED',
                        table         => 'derived(union(actor_1,actor_2))',
                        possible_keys => undef,
                        partitions    => undef,
                        children      => [
                           {  type     => 'Table scan',
                              id       => 2,
                              rowid    => 3,
                              rows     => undef,
                              children => [
                                 {  type          => 'UNION',
                                    possible_keys => undef,
                                    partitions    => undef,
                                    table         => 'union(actor_1,actor_2)',
                                    children      => [
                                       {  type          => 'Index scan',
                                          key           => 'actor_1->PRIMARY',
                                          possible_keys => undef,
                                          partitions    => undef,
                                          key_len       => 2,
                                          'ref'         => undef,
                                          rows          => 200,
                                          id            => 2,
                                          rowid         => 1,
                                       },
                                       {  type          => 'Index scan',
                                          key           => 'actor_2->PRIMARY',
                                          possible_keys => undef,
                                          partitions    => undef,
                                          key_len       => 2,
                                          'ref'         => undef,
                                          rows          => 200,
                                          id            => 3,
                                          rowid         => 2,
                                       },
                                    ],
                                 },
                              ],
                           }
                        ],
                     },
                  ],
               },
               {  type     => 'Table scan',
                  id       => 4,
                  rowid    => 4,
                  rows     => 400,
                  children => [
                     {  type          => 'DERIVED',
                        table         => 'derived(union(actor_3,actor_4))',
                        possible_keys => undef,
                        partitions    => undef,
                        children      => [
                           {  type     => 'Table scan',
                              rows     => undef,
                              id       => 5,
                              rowid    => 7,
                              children => [
                                 {  type          => 'UNION',
                                    possible_keys => undef,
                                    partitions    => undef,
                                    table         => 'union(actor_3,actor_4)',
                                    children      => [
                                       {  type          => 'Index scan',
                                          key           => 'actor_3->PRIMARY',
                                          possible_keys => undef,
                                          partitions    => undef,
                                          key_len       => 2,
                                          'ref'         => undef,
                                          rows          => 200,
                                          id            => 5,
                                          rowid         => 5,
                                       },
                                       {  type          => 'Index scan',
                                          key           => 'actor_4->PRIMARY',
                                          possible_keys => undef,
                                          partitions    => undef,
                                          key_len       => 2,
                                          'ref'         => undef,
                                          rows          => 200,
                                          id            => 6,
                                          rowid         => 6,
                                       },
                                    ],
                                 },
                              ]
                           },
                        ],
                     },
                  ],
               }
            ],
         },
      ],
   },
   'Union over two derived tables of unions',
);

$t = $e->parse( load_file('samples/simple_subquery.sql') );
is_deeply(
   $t,
   {  type     => 'SUBQUERY',
      children => [
         {  type          => 'Index scan',
            rows          => 200,
            id            => 1,
            rowid         => 0,
            key_len       => 2,
            key           => 'actor->PRIMARY',
            possible_keys => undef,
            partitions    => undef,
            'ref'         => undef,
         },
         {  type          => 'Index scan',
            key           => 'film->idx_fk_language_id',
            possible_keys => undef,
            partitions    => undef,
            key_len       => 1,
            'ref'         => undef,
            rows          => 951,
            id            => 2,
            rowid         => 1,
         },
      ]
   },
   'Simple subquery',
);

$t = $e->parse( load_file('samples/dependent_subquery.sql') );
is_deeply(
   $t,
   {  type     => 'DEPENDENT SUBQUERY',
      children => [
         {  type          => 'Index scan',
            rows          => 200,
            id            => 1,
            rowid         => 0,
            key_len       => 2,
            key           => 'actor->PRIMARY',
            possible_keys => undef,
            partitions    => undef,
            'ref'         => undef,
         },
         {  type     => 'Filter with WHERE',
            id       => 2,
            rowid    => 1,
            children => [
               {  type          => 'Index lookup',
                  key           => 'film_actor->PRIMARY',
                  possible_keys => 'PRIMARY',
                  partitions    => undef,
                  key_len       => 2,
                  'ref'         => 'actor.actor_id',
                  rows          => 13,
               },
            ],
         },
      ],
   },
   'Dependent subquery',
);

$t = $e->parse( load_file('samples/uncacheable_subquery.sql') );
is_deeply(
   $t,
   {  type     => 'UNCACHEABLE SUBQUERY',
      children => [
         {  type          => 'Index scan',
            rows          => 200,
            id            => 1,
            rowid         => 0,
            key_len       => 2,
            key           => 'actor->PRIMARY',
            possible_keys => undef,
            partitions    => undef,
            'ref'         => undef,
         },
         {  type          => 'Index scan',
            key           => 'actor->PRIMARY',
            possible_keys => undef,
            partitions    => undef,
            key_len       => 2,
            'ref'         => undef,
            rows          => 200,
            id            => 2,
            rowid         => 1,
         },
      ],
   },
   'Dependent subquery',
);

$t = $e->parse( load_file('samples/join_in_subquery.sql') );
is_deeply(
   $t,
   {  type     => 'SUBQUERY',
      children => [
         {  type          => 'Index scan',
            rows          => 200,
            id            => 1,
            rowid         => 0,
            key_len       => 2,
            key           => 'actor->PRIMARY',
            possible_keys => undef,
            partitions    => undef,
            'ref'         => undef,
         },
         {  type     => 'JOIN',
            children => [
               {  type          => 'Index scan',
                  key           => 'film->idx_fk_language_id',
                  key_len       => 1,
                  possible_keys => 'PRIMARY',
                  partitions    => undef,
                  'ref'         => undef,
                  rows          => 951,
                  id            => 2,
                  rowid         => 1,
               },
               {  type          => 'Index lookup',
                  key           => 'film_actor->idx_fk_film_id',
                  possible_keys => 'idx_fk_film_id',
                  partitions    => undef,
                  key_len       => 2,
                  'ref'         => 'sakila.film.film_id',
                  rows          => 2,
                  id            => 2,
                  rowid         => 2,
               },
            ],
         },
      ],
   },
   'Join inside a subquery',
);

$t = $e->parse( load_file('samples/unique_subquery_in_where_clause.sql') );
is_deeply(
   $t,
   {  type     => 'DEPENDENT SUBQUERY',
      children => [
         {  type     => 'Filter with WHERE',
            id       => 1,
            rowid    => 0,
            children => [
               {  type          => 'Index scan',
                  rows          => 5143,
                  key_len       => 2,
                  key           => 'film_actor->idx_fk_film_id',
                  possible_keys => undef,
                  partitions    => undef,
                  'ref'         => undef,
               },
            ],
         },
         {  type          => 'Unique subquery',
            rows          => 1,
            id            => 2,
            rowid         => 1,
            key_len       => 2,
            key           => 'actor->PRIMARY',
            possible_keys => 'PRIMARY',
            partitions    => undef,
            'ref'         => 'func',
         },
      ],
   },
   'Unique subquery',
);

$t = $e->parse( load_file('samples/index_subquery_in_where_clause.sql') );
is_deeply(
   $t,
   {  type     => 'DEPENDENT SUBQUERY',
      children => [
         {  type     => 'Filter with WHERE',
            id       => 1,
            rowid    => 0,
            children => [
               {  type          => 'Index scan',
                  rows          => 200,
                  key_len       => 2,
                  key           => 'actor->PRIMARY',
                  possible_keys => undef,
                  partitions    => undef,
                  'ref'         => undef,
               },
            ],
         },
         {  type          => 'Index subquery',
            rows          => 13,
            id            => 2,
            rowid         => 1,
            key_len       => 2,
            key           => 'film_actor->PRIMARY',
            possible_keys => 'PRIMARY',
            partitions    => undef,
            'ref'         => 'func',
         },
      ],
   },
   'Index subquery',
);

$t = $e->parse( load_file('samples/full_scan_on_null_key.sql') );
is_deeply(
   $t,
   {  type     => 'DEPENDENT SUBQUERY',
      children => [
         {  type     => 'Filter with WHERE',
            id       => 1,
            rowid    => 0,
            children => [
               {  type     => 'Table scan',
                  rows     => 4,
                  children => [
                     {  type          => 'Table',
                        table         => 't1',
                        possible_keys => undef,
                        partitions    => undef,
                     },
                  ],
               },
            ],
         },
         {  type     => 'JOIN',
            children => [
               {  type     => 'Filter with WHERE',
                  id       => 2,
                  rowid    => 1,
                  children => [
                     {  type          => 'Unique index lookup',
                        rows          => 1,
                        key_len       => 4,
                        key           => 't2->PRIMARY',
                        possible_keys => 'PRIMARY',
                        partitions    => undef,
                        'ref'         => 'func',
                        warning       => 'Full scan on NULL key',
                     },
                  ],
               },
               {  type     => 'Filter with WHERE',
                  id       => 2,
                  rowid    => 2,
                  children => [
                     {  type     => 'Bookmark lookup',
                        children => [
                           {  type          => 'Unique index lookup',
                              rows          => 1,
                              key_len       => 4,
                              key           => 't3->PRIMARY',
                              'ref'         => 'func',
                              warning       => 'Full scan on NULL key',
                              possible_keys => 'PRIMARY',
                              partitions    => undef,
                           },
                           {  type          => 'Table',
                              table         => 't3',
                              possible_keys => 'PRIMARY',
                              partitions    => undef,
                           },
                        ],
                     },
                  ],
               },
            ],
         },
      ],
   },
   'Subqueries that do a full scan on a NULL key',
);
