#!/usr/bin/perl -W
# Usage: arcconf GETCONFIG 1

if ($#ARGV == 1 && $ARGV[0] eq 'GETCONFIG' && $ARGV[1] eq '1') {
print << '[END]';
Controllers found: 1
----------------------------------------------------------------------
Controller information
----------------------------------------------------------------------
   Controller Status                        : Optimal
   Channel description                      : SAS/SATA
   Controller Model                         : ICP ICP5085BL
   Controller Serial Number                 : 1234567890A
   Physical Slot                            : 5
   Temperature                              : 37 C/ 98 F (Normal)
   Installed memory                         : 256 MB
   Copyback                                 : Disabled
   Background consistency check             : Disabled
   Automatic Failover                       : Enabled
   Defunct disk drive count                 : 0
   Logical devices/Failed (error)/Degraded  : 1/0/0
   --------------------------------------------------------
   Controller Version Information
   --------------------------------------------------------
   BIOS                                     : 5.2-0 (15323)
   Firmware                                 : 5.2-0 (15323)
   Driver                                   : 1.1-5 (2409)
   Boot Flash                               : 5.2-0 (15323)
   --------------------------------------------------------
   Controller Battery Information
   --------------------------------------------------------
   Status                                   : Optimal
   Over temperature                         : No
   Capacity remaining                       : 100 percent
   Time remaining (at current draw)         : 3 days, 1 hours, 31 minutes

----------------------------------------------------------------------
Logical device information
----------------------------------------------------------------------
Logical device number 0
   Logical device name                      : 
   RAID level                               : 10
   Status of logical device                 : Optimal
   Size                                     : 560332 MB
   Stripe-unit size                         : 256 KB
   Read-cache mode                          : Enabled
   Write-cache mode                         : Enabled (write-back)
   Write-cache setting                      : Enabled (write-back) when protected by battery
   Partitioned                              : Yes
   Protected by Hot-Spare                   : No
   Bootable                                 : Yes
   Failed stripes                           : No
   --------------------------------------------------------
   Logical device segment information
   --------------------------------------------------------
   Group 0, Segment 0                       : Present (0,4) 
   Group 0, Segment 1                       : Present (0,5) 
   Group 1, Segment 0                       : Present (0,6) 
   Group 1, Segment 1                       : Present (0,7) 
   Group 2, Segment 0                       : Present (0,0) 
   Group 2, Segment 1                       : Present (0,1) 
   Group 3, Segment 0                       : Present (0,2) 
   Group 3, Segment 1                       : Present (0,3) 


----------------------------------------------------------------------
Physical Device information
----------------------------------------------------------------------
      Device #0
         Device is a Hard drive
         State                              : Online
         Supported                          : Yes
         Transfer Speed                     : SAS 3.0 Gb/s
         Reported Channel,Device            : 0,0
         Reported Location                  : Connector 0, Device 0
         Vendor                             : FUJITSU
         Model                              : MBA3147RC
         Firmware                           : 0103
         World-wide name                    : 500000E012345670
         Size                               : 140272 MB
         Write Cache                        : Enabled (write-back)
         FRU                                : None
         S.M.A.R.T.                         : No
      Device #1
         Device is a Hard drive
         State                              : Online
         Supported                          : Yes
         Transfer Speed                     : SAS 3.0 Gb/s
         Reported Channel,Device            : 0,1
         Reported Location                  : Connector 0, Device 1
         Vendor                             : FUJITSU
         Model                              : MBA3147RC
         Firmware                           : 0103
         World-wide name                    : 500000E012345671
         Size                               : 140272 MB
         Write Cache                        : Enabled (write-back)
         FRU                                : None
         S.M.A.R.T.                         : No
      Device #2
         Device is a Hard drive
         State                              : Online
         Supported                          : Yes
         Transfer Speed                     : SAS 3.0 Gb/s
         Reported Channel,Device            : 0,2
         Reported Location                  : Connector 0, Device 2
         Vendor                             : FUJITSU
         Model                              : MBA3147RC
         Firmware                           : 0103
         World-wide name                    : 500000E012345672
         Size                               : 140272 MB
         Write Cache                        : Enabled (write-back)
         FRU                                : None
         S.M.A.R.T.                         : No
      Device #3
         Device is a Hard drive
         State                              : Online
         Supported                          : Yes
         Transfer Speed                     : SAS 3.0 Gb/s
         Reported Channel,Device            : 0,3
         Reported Location                  : Connector 0, Device 3
         Vendor                             : FUJITSU
         Model                              : MBA3147RC
         Firmware                           : 0103
         World-wide name                    : 500000E012345673
         Size                               : 140272 MB
         Write Cache                        : Enabled (write-back)
         FRU                                : None
         S.M.A.R.T.                         : No
      Device #4
         Device is a Hard drive
         State                              : Online
         Supported                          : Yes
         Transfer Speed                     : SAS 3.0 Gb/s
         Reported Channel,Device            : 0,4
         Reported Location                  : Connector 1, Device 0
         Vendor                             : FUJITSU
         Model                              : MBA3147RC
         Firmware                           : 0103
         World-wide name                    : 500000E012345674
         Size                               : 140272 MB
         Write Cache                        : Enabled (write-back)
         FRU                                : None
         S.M.A.R.T.                         : No
      Device #5
         Device is a Hard drive
         State                              : Online
         Supported                          : Yes
         Transfer Speed                     : SAS 3.0 Gb/s
         Reported Channel,Device            : 0,5
         Reported Location                  : Connector 1, Device 1
         Vendor                             : FUJITSU
         Model                              : MBA3147RC
         Firmware                           : 0103
         World-wide name                    : 500000E012345675
         Size                               : 140272 MB
         Write Cache                        : Enabled (write-back)
         FRU                                : None
         S.M.A.R.T.                         : No
      Device #6
         Device is a Hard drive
         State                              : Online
         Supported                          : Yes
         Transfer Speed                     : SAS 3.0 Gb/s
         Reported Channel,Device            : 0,6
         Reported Location                  : Connector 1, Device 2
         Vendor                             : FUJITSU
         Model                              : MBA3147RC
         Firmware                           : 0103
         World-wide name                    : 500000E012345676
         Size                               : 140272 MB
         Write Cache                        : Enabled (write-back)
         FRU                                : None
         S.M.A.R.T.                         : No
      Device #7
         Device is a Hard drive
         State                              : Online
         Supported                          : Yes
         Transfer Speed                     : SAS 3.0 Gb/s
         Reported Channel,Device            : 0,7
         Reported Location                  : Connector 1, Device 3
         Vendor                             : FUJITSU
         Model                              : MBA3147RC
         Firmware                           : 0103
         World-wide name                    : 500000E012345677
         Size                               : 140272 MB
         Write Cache                        : Enabled (write-back)
         FRU                                : None
         S.M.A.R.T.                         : No
      Device #8
         Device is an Enclosure services device
         Reported Channel,Device            : 2,0
         Enclosure ID                       : 0
         Type                               : SES2
         Vendor                             : ADAPTEC
         Model                              : Virtual SGPIO  0
         Firmware                           : 0001
         Status of Enclosure services device
            Temperature                     : Normal


Command completed successfully.
[END]
}
