#!/usr/bin/perl -W
# Usage: tw_cli /c0 show all

if ($#ARGV == 2 && $ARGV[0] eq '/c0' && $ARGV[1] eq 'show' && $ARGV[2] eq 'all') {
print << '[END]';
/c0 Driver Version = 2.26.02.010
/c0 Model = 9550SXU-4LP
/c0 Memory Installed  = 112MB
/c0 Firmware Version = FE9X 3.08.02.007
/c0 Bios Version = BE9X 3.08.00.002
/c0 Monitor Version = BL9X 3.02.00.001
/c0 Serial Number = 123456789012345
/c0 PCB Version = Rev 032
/c0 PCHIP Version = 1.60
/c0 ACHIP Version = 1.90
/c0 Number of Ports = 4
/c0 Number of Units = 1
/c0 Number of Drives = 2
/c0 Total Optimal Units = 1
/c0 Not Optimal Units = 0 
/c0 JBOD Export Policy = off
/c0 Disk Spinup Policy = 1
/c0 Spinup Stagger Time Policy (sec) = 1
/c0 Auto-Carving Policy = off
/c0 Auto-Carving Size = 2048 GB
/c0 Auto-Rebuild Policy = on
/c0 Controller Bus Type = PCIX
/c0 Controller Bus Width = 64 bits
/c0 Controller Bus Speed = 133 Mhz

Unit  UnitType  Status         %Cmpl  Stripe  Size(GB)  Cache  AVerify  IgnECC
------------------------------------------------------------------------------
u0    RAID-1    OK             -      -       465.651   ON     OFF      OFF      

Port   Status           Unit   Size        Blocks        Serial
---------------------------------------------------------------
p0     OK               u0     465.76 GB   976773168     12345678            
p1     OK               u0     465.76 GB   976773168     12345679            
p2     NOT-PRESENT      -      -           -             -
p3     NOT-PRESENT      -      -           -             -

Name  OnlineState  BBUReady  Status    Volt     Temp     Hours  LastCapTest
---------------------------------------------------------------------------
bbu   On           Yes       OK        OK       OK       255    25-Oct-2007  

[END]
}
