#!/bin/bash

if [ "$1" == "" ]
then
    echo "syntax my sql{dump|binlog|admin} arguments"
    exit
fi

export LD_LIBRARY_PATH=/home/baron/mysql_source/5.0.45/lib:/home/baron/mysql_source/5.0.45/lib/mysql:$LD_LIBRARY_PATH
export DYLD_LIBRARY_PATH=/home/baron/mysql_source/5.0.45/lib:/home/baron/mysql_source/5.0.45/lib/mysql:$DYLD_LIBRARY_PATH
MYSQL='/home/baron/mysql_source/5.0.45/bin/mysql'

SUFFIX=$1
shift

MYSQLCMD="/home/baron/mysql_source/5.0.45/bin/my$SUFFIX"

if [ -f $MYSQLCMD ]
then
    $MYSQLCMD --defaults-file=/home/baron/rsandbox_5_0_45/master/my.sandbox.cnf "$@"
else
    echo "$MYSQLCMD not found "
fi

